spring:
  data:
    cassandra:
      keyspace-name: user_connector
      contact-points: 127.0.0.1
      port: 9042
      local-datacenter: datacenter1
  kafka:
    bootstrap-servers: localhost:9092

