spring:
  data:
    cassandra:
      keyspace-name: user_connector
      contact-points: ${CASSANDRA_CONTACT_POINT:127.0.0.1}
      port: 9042
      local-datacenter: datacenter1
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

